#sudo docker compose up -d
services:
  fluentd:
    image: fluentd_prueba:latest
    container_name: fluentd_prueba_container
    volumes:
      - /var/log:/var/log:ro
      - /var/log/journal:/var/log/journal:ro
      - ./logs/syslog:/fluentd/log #FIXME need to be changed, for testing only
    ports:
      - "24231:24231"
      - "24220:24220" #Esto es de prueba para acceder via web mediante localhost:24220/api/plugins.json
    restart: unless-stopped

